#!/usr/bin/env sh

# Remove old dist files
rm -r dist/*

# Build package
python setup.py sdist bdist_wheel

# Upload package
python -m twine upload dist/*

# Clean up files
rm -r build spotlight.egg-info
