#!/usr/bin/env sh

# Delete all python cache files
find . -name '*.pyc' -delete
rm -rf .pytest_cache .tmontmp .testmondata

TEST_CMD="python -B -m pytest"
TEST_PATH="tests"
COVERAGE_FLAG="--cov=spotlight"

if [[ $1 = "-c" ]] || [[ $1 = "--cov" ]]; then
    ${TEST_CMD} --cov-report=xml ${COVERAGE_FLAG} ${TEST_PATH}
    exit 0
fi

if [[ -z "$1" ]]; then
    ${TEST_CMD} ${COVERAGE_FLAG} ${TEST_PATH}
    exit 0
fi

${TEST_CMD} $1
